controllers:
    resource: ../src/Controller/
    type: attribute

accueil:
    path: /
    controller: App\Controller\AccueilController::index

postuler:
    path: /postuler
    controller: App\Controller\AccueilController::postuler

dashboard_company:
    path: /employeur/dashboard
    controller: App\Controller\EmployeurController::dashboardCompany

ad:
    path: /employeur/ad
    controller: App\Controller\EmployeurController::ad

editad:
    path: /employeur/ad/{id}
    controller: App\Controller\EmployeurController::editad

seeapplicants:
    path: /employeur/seeapplicants/{id}
    controller: App\Controller\EmployeurController::seeapplicants

deletead:
    path: /employeur/deletead/{id}
    controller: App\Controller\EmployeurController::deletead

check_database:
    path: /check-database
    controller: App\Controller\AccueilController::checkDatabase

deleteuser:
    path: /deleteuser
    controller: App\Controller\AccueilController::deleteuser

updateuser:
    path: /updateuser
    controller: App\Controller\AccueilController::updateuser

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\SecurityController::register

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout